### ISSUE TITLE
Support RISC-V Zb[a,b,c,s] extensions

### ISSUE THREAD

**Issue by stephanosio** [zephyrproject-rtos/sdk-ng#486]
## Preface

[GCC 12.1 now supports the RISC-V bit manipulation instructions](https://gcc.gnu.org/gcc-12/changes.html):

> New ISA extension support for zba, zbb, zbc, zbs was added.

Ensure that RISC-V Zba, Zbb, Zbc and Zbs extension features are properly supported by the Zephyr SDK.

#### References

* https://github.com/bminor/binutils-gdb/commit/80d49d6a1b865c84a8596da465db285cbbdfd1bb
* https://github.com/bminor/binutils-gdb/commit/9455c91957590ca6d4520cfe0955f9f9f1349f82

#### Tasks

- [x] Ensure that Zb[a,b,c,s] extensions are supported by the Binutils (assembler).
- [x] Ensure that Zb[a,b,c,s] extensions are supported by the GDB.

#### References

* [New ISA extension support for zba, zbb, zbc, zbs was added.](https://gcc.gnu.org/gcc-12/changes.html)

#### Tasks

- [x] Ensure that Zb[a,b,c,s] instructions can be properly selected using `-march`.
- [x] Ensure that Zb[a,b,c,s] instructions are properly emitted by the code generator.

#### References

* https://github.com/qemu/qemu/commit/878dd0e9ac18af657dcbdb598bb2eb1278606d3a
* https://github.com/qemu/qemu/commit/16c38f36f5cb42bbfe7b9cd4bb29206a3ecab760

#### Tasks

- [x] Ensure that the virt machine properly emulates the Zb[a,b,c,s] instructions.

#### Notes

* Newlib does not have native support for the RISC-V Bitmanip instructions.

#### Tasks

- [x] Ensure that the Zb[a,b,c,s] instructions are properly utilised by the Newlib compiled using the GCC 12.1.

**Comment by stephanosio** [comment]
Consider implementing proper RV32E and Zb[a,b,c,s] coverage in https://github.com/zephyrproject-rtos/zephyr/pull/45930.

**Comment by stephanosio** [comment]
cc @carlocaione

**Comment by stephanosio** [comment]
Verified in #509 using the toolchain build from https://github.com/zephyrproject-rtos/sdk-ng/actions/runs/2581051871:

```
GNU assembler (Zephyr SDK 0.14.2-55-g715dd86) 2.38
riscv64-zephyr-elf-gcc (Zephyr SDK 0.14.2-55-g715dd86) 12.1.0
GNU gdb (Zephyr SDK 0.14.2-55-g715dd86) 12.1
```

> Ensure that Zb[a,b,c,s] extensions are supported by the Binutils (assembler).

Binutils successfully builds the Zba, Zbb, Zbc, Zbs instructions in https://github.com/riscv/riscv-bitmanip/blob/main-history/tools/riscv-binutils-demo.s

> Ensure that Zb[a,b,c,s] instructions can be properly selected using -march.
> Ensure that Zb[a,b,c,s] instructions are properly emitted by the code generator.

The `tests/crypto/mbedtls` test was built for `-march=rv32im_zba_zbb_zbc_zbs` using the GCC and the listing output was verified to contain the Bitmanip instructions:

```
        return 31 - __builtin_clz(usable_sz);
800018b0:       60041413                clz     s0,s0
```

```
                int minbucket = __builtin_ctz(bmask);
800019f8:       60141613                ctz     a2,s0
```

```
    if( ilen + 2 * hlen + 2 < ilen || olen < ilen + 2 * hlen + 2 )
8000bf68:       00151c13                slli    s8,a0,0x1
8000bf6c:       20f527b3                sh1add  a5,a0,a5
8000bf70:       fb37e5e3                bltu    a5,s3,8000bf1a <mbedtls_rsa_rsaes_oaep_encrypt+0x20>
8000bf74:       faf4e3e3                bltu    s1,a5,8000bf1a <mbedtls_rsa_rsaes_oaep_encrypt+0x20>
```

> Ensure that the virt machine properly emulates the Zb[a,b,c,s] instructions.

The above test (`tests/crypto/mbedtls`) build was run inside the QEMU and it passed.

>  Ensure that Zb[a,b,c,s] extensions are supported by the GDB.

The above test (`tests/crypto/mbedtls`) build was run inside the QEMU with the debug server enabled and the GDB connected to it.

```
Breakpoint 3, mbedtls_mpi_get_bit (X=<optimized out>, pos=0) at /home/stephanos/Dev/zephyrproject/modules/crypto/mbedt
ls/library/bignum.c:302
=> 0x800068fc <mbedtls_mpi_get_bit+8>:  18 45   lw      a4,8(a0)
=> 0x800068fe <mbedtls_mpi_get_bit+10>: 93 d7 55 00     srli    a5,a1,0x5
=> 0x80006902 <mbedtls_mpi_get_bit+14>: b3 c7 e7 20     sh2add  a5,a5,a4
```

> Ensure that the Zb[a,b,c,s] instructions are properly utilised by the Newlib compiled using the GCC 12.1.

Disassembling the `libc.a` from the `rv32im_zicsr_zifencei_zba_zbb_zbc_zbs/ilp32` multilib:

```
   0:   60151793                ctz     a5,a0
   0:   60151793                ctz     a5,a0
   8:   60051513                clz     a0,a0
   8:   60051513                clz     a0,a0
  10:   60059593                clz     a1,a1
  1c:   60051513                clz     a0,a
```

```
-elf/lib/rv32im_zicsr_zifencei_zba_zbb_zbc_zbs/ilp32/libc.a | grep sh.add
  9c:   20f745b3                sh2add  a1,a4,a5
  60:   2124c4b3                sh2add  s1,s1,s2
  a8:   20d74733                sh2add  a4,a4,a3
 184:   20d74733                sh2add  a4,a4,a3
 290:   2149ca33                sh2add  s4,s3,s4
 3ec:   20e7c7b3                sh2add  a5,a5,a4
  94:   20f567b3                sh3add  a5,a0,a5
  8c:   214b4b33                sh2add  s6,s6,s4
  50:   20974733                sh2add  a4,a4,s1
  6c:   20954533                sh2add  a0,a0,s1
  20:   20d6a6b3                sh1add  a3,a3,a3
  44:   20c62633                sh1add  a2,a2,a2
 210:   20f767b3                sh3add  a5,a4,a5
 2ac:   20e7e7b3                sh3add  a5,a5,a4
 5a8:   21242a33                sh1add  s4,s0,s2
  30:   2067a7b3                sh1add  a5,a5,t1
  38:   2084c9b3                sh2add  s3,s1,s0
  40:   2144c333                sh2add  t1,s1,s4
 174:   2144c7b3                sh2add  a5,s1,s4
...
```
